image: registry.gitlab.com/gifnksm/docker-mdbook-ja:latest

stages:
    - build
    - deploy

build-book:
    stage: build
    before_script:
        - docker/setup-build-env
        - apt-get update
        - apt-get install -y --no-install-recommends make bash git
    script:
        - make build
        - make check -k
    artifacts:
        paths:
            - book

pages:
    stage: deploy
    dependencies:
        - build-book
    script:
        - mv book/html public
    artifacts:
        paths:
            - public
