[book]
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
title = "mdbook-ja-templateユーザーズガイド"
language = "ja"
src = "src"
multilingual = false

[output.html]
mathjax-support = true
additional-js = ["js/mermaid.min.js", "js/mermaid-init.js"]
git-repository-url = "https://github.com/gifnksm/mdbook-ja-template"
edit-url-template = "https://github.com/gifnksm/mdbook-ja-template/edit/main/{path}"
site-url = "/mdbook-ja-template/"

[output.linkcheck]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
