version: '3.9'

x-service:
  &default-service
  build:
    context: docker
    args:
      BASE_IMAGE: ${DOCKER_BASE_IMAGE:-ghcr.io/gifnksm/mdbook-ja:latest}
  image: mdbook
  init: true
  volumes: [".:/book:rw"]
  network_mode: "host"
  user: "${UID}:${GID}"

services:
  mdbook:
    <<: *default-service
    entrypoint: ["mdbook"]
    command: ["serve"]

  mdbook-mermaid:
    <<: *default-service
    entrypoint: ["mdbook-mermaid"]

  mdbook-linkcheck:
    <<: *default-service
    entrypoint: ["mdbook-linkcheck"]

  markdownlint:
    <<: *default-service
    entrypoint: ["markdownlint"]

  textlint:
    <<: *default-service
    entrypoint: ["textlint"]

  exec:
    <<: *default-service
    entrypoint: []
